# Generated by Django 3.2.9 on 2022-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("client", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="clientmodel",
            name="password",
            field=models.CharField(default="", max_length=30),
        )
    ]
